import "server-only";

import { z } from "zod";

import raw from "./content/problems.json";
import { type Problem, ProblemSchema, type ProblemSummary } from "./schemas";

/*
 * The problem set is bundled with the app (generated by `npm run
 * coding:generate` from scripts/coding/problems), so a deploy always ships the
 * current problems. Only users' progress is stored.
 */

let problems: Problem[] | null = null;
let bySlug: Map<string, Problem> | null = null;

export function allProblems(): Problem[] {
  problems ??= z.array(ProblemSchema).parse((raw as unknown as { problems: unknown }).problems);
  return problems;
}

export function getProblem(slug: string): Problem | null {
  bySlug ??= new Map(allProblems().map((problem) => [problem.slug, problem]));
  return bySlug.get(slug) ?? null;
}

export function problemSummaries(): ProblemSummary[] {
  return allProblems().map(({ slug, title, difficulty, topics, skill, leetcodeUrl }) => ({
    slug,
    title,
    difficulty,
    topics,
    skill,
    leetcodeUrl,
  }));
}

/** Number of tests a submission must run (examples + hidden). */
export function testCount(problem: Problem): number {
  return problem.examples.length + problem.hiddenTests.length;
}
