import "server-only";

import { type ContentFile, contentPath } from "@/lib/storage/paths";
import { type SeedFile, ensureSeeded } from "@/lib/storage/seed";

import behavioral from "./content/behavioral-questions.json";
import competencies from "./content/competencies.json";
import interviewerQuestions from "./content/interviewer-questions.json";
import questions from "./content/questions.json";
import resources from "./content/resources.json";
import roles from "./content/roles.json";
import prerequisites from "./content/topic-prerequisites.json";
import topics from "./content/topics.json";
import tracks from "./content/tracks.json";

/**
 * Seed content bundled with the app (generated by `npm run seed:generate`).
 * Only content is seeded; users and private data never are.
 */
export const CONTENT_SEED: Record<ContentFile, unknown> = {
  "tracks.json": tracks,
  "roles.json": roles,
  "competencies.json": competencies,
  "topics.json": topics,
  "topic-prerequisites.json": prerequisites,
  "questions.json": questions,
  "resources.json": resources,
  "behavioral-questions.json": behavioral,
  "interviewer-questions.json": interviewerQuestions,
};

/** Copies seed content into DATA_DIR for any content file that does not exist yet. */
export async function seedContentIfMissing(): Promise<string[]> {
  const files: SeedFile[] = Object.entries(CONTENT_SEED).map(([file, envelope]) => ({
    target: contentPath(file as ContentFile),
    envelope,
  }));
  return ensureSeeded(files);
}
